### ISSUE TITLE
Provide `zip`

### ISSUE THREAD

**Issue by t1** [wildfly-extras/wildfly-graphql-feature-pack#10]
We don't use galleon, so it would be very convenient for us, if we could get a `zip` containing the three directories `io/smallrye/graphql`, `org/eclipse/microprofile/graphql`, and `org/wildfly/extension/microprofile/graphql-smallrye` relative to the WildFly home, i.e. under `modules/system/layers/base/`.

The necessary changes to the `standalone.xml` could be provided as a cli-script.

**Comment by t1** [comment]
The script would be:

```
/extension=org.wildfly.extension.microprofile.graphql-smallrye:add
/subsystem=microprofile-graphql-smallrye:add
```

**Comment by jmartisk** [comment]
I'm thinking whether there is any clean way to do this using WildFly tooling directly. I suppose there isn't, but... perhaps @aloubyansky knows - is there a straightforward way to produce an overlay ZIP from a built feature pack, so that you could unzip it over a WildFly distribution?
If not, we could provide an additional Maven module that zips up the necessary artifacts from the `build` module

**Comment by aloubyansky** [comment]
Just to clarify, are you asking for a provisioning tool that would "install" that kind of package?

**Comment by jmartisk** [comment]
Given that @t1 says they don't use Galleon, I would 'guess' they don't want to use any provisioning tool for installation, just produce a zip (correct me if I'm wrong)

**Comment by t1** [comment]
Correct: we install by simply unzipping the downloaded WildFly and a zip I created myself manually. I'd like to not do that for each new release but simply download it as well. And we wouldn't have to host the zip ourselves.

And before you ask: we apply a cli script with an embedded wildfly.

**Comment by jmartisk** [comment]
So @aloubyansky is there something you would suggest? Otherwise we'll probably just bake a custom script that packages the zip

**Comment by aloubyansky** [comment]
I still don't fully understand what the issue is about. It's not just a zip as you describe it @jmartisk, there is also a script that needs to be executed. If you are not asking for a tool to do that, it will have to be done "by hand". If that's what you prefer then that's the end of it, I suppose. Unless you also want others to be able to depend on and automatically install your extension when their extensions are installed.

Interestingly, afaiu, what @t1 describes here https://github.com/wildfly-extras/wildfly-graphql-feature-pack/issues/10#issuecomment-689096432 is pretty much exactly what Galleon does: download the zip from maven and run the script using the embedded wildfly.

**Comment by t1** [comment]
I just would like to have a different packaging format with only the zip. I will do the rest with other means.
