### ISSUE TITLE
Release with SmallRye GraphQL 1.9.0

### ISSUE THREAD

**Issue by t1** [wildfly-extras/wildfly-graphql-feature-pack#108]
The newest 1.x release is 1.8.0 that contains SmallRye GraphQL 1.7.0. There have been 6 1.x releases, since.

Can we have a last update before going to WF 17, please? 🙂

**Comment by jmartisk** [comment]
I can make a release with smallrye-graphql 1.7.1 if that helps, but not with 1.8/1.9, because these are incompatible with WildFly <27 due to Jandex major version mismatch. 1.8 and 1.9 are basically skipped by the feature pack, with the suggested migration straight to smallrye-graphql 2.0 (feature pack 2.0, wildfly 27).

**Comment by jmartisk** [comment]
We'd have to maintain a separate 'branch' of smallrye-graphql 1.9 that uses the older Jandex 2.x version. We thought it's not worth the hassle just to be able to support wildfly 26, when 27 is already available.

**Comment by t1** [comment]
Oh, yes.... sorry, you mentioned that before. 1.7.1 is not worth it.
