### ISSUE TITLE
Distribute binaries

### ISSUE THREAD

**Issue by t1** [wildfly-extras/wildfly-graphql-feature-pack#49]
I didn't find the binaries ready for download anywhere. Not on Maven Central nor a distribution management section in the pom nor a link in the readme. Did I miss something?

**Comment by jmartisk** [comment]
All Maven artifacts are in Maven Central (https://repo.maven.apache.org/maven2/org/wildfly/extras/graphql/wildfly-microprofile-graphql-feature-pack/) because it is assumed they will be consumed by the Galleon tool, which downloads them using Maven. Galleon is the recommended way to provision WF instances and install feature packs.

Do you require the built 'overlay' zip to be downloadable without having to run your own build from a tag? If so, I could start attaching it to Github releases. Even though I don't really like it - it comes with issues - for example you have to manually update the WF configuration files when installing the pack this way, and it doesn't know whether you have the reactive pack installed or not (and part of the reactive pack is a dependency of the graphql pack).

**Comment by t1** [comment]
We manage the `standalone.xml` completely differently, so that would not be an issue for us (and probably others, too). So the `overlay` would help us a lot.

I wasn't aware that we also need the reactive pack; what are the maven coordinates for that? We would need that overlay, too, then.

**Comment by jmartisk** [comment]
The [reactive feature pack](https://github.com/wildfly-extras/wildfly-mp-reactive-feature-pack) does not provide any overlay (unless you persuade its maintainer to do it too) so the GraphQL overlay will have to contain the necessary parts from the reactive pack too, to make sure that the overlay is enough to get GraphQL working. 
I realized that the 1.1.x branch does not do this, right now I am in the process of preparing the release of GraphQL feature pack 1.2.0 and that should contain the reactive stuff. If you build the current `main` branch from this repo, it should be there.

I added a section to the installation guide with instructions how to activate everything: https://github.com/wildfly-extras/wildfly-graphql-feature-pack/wiki/Installation-guide#installing-without-galleon - right now it only applies to the upcoming 1.2 release, I suppose I could fix the 1.1.x branch too, and then release 1.1.1

**Comment by t1** [comment]
I finally managed to try it out: this is exactly what we need. Works like a charm. Thanks a lot!

I have opened an issue in our project to move from the packaged SmallRye GraphQL to the feature pack, which requires additional Ansible magic, but I think it's worth it.

Two little questions, I'm not sure if they deserve a separate issue:
1. If you could distribute the overlay on Maven Central, we could cache it in our Artifactory and we'd have fewer hassle with firewalls.
2. Would it be feasible to have the `graphiql-ui` as a module, too? It could be en/disabled in the WildFly config file.

**Comment by jmartisk** [comment]
>     1. If you could distribute the overlay on Maven Central, we could cache it in our Artifactory and we'd have fewer hassle with firewalls.

I'm not sure how difficult that would be, I can have a look some time to assess. Or you are welcome to submit a PR which does it if you know how ;)

>     2. Would it be feasible to have the `graphiql-ui` as a module, too? It could be en/disabled in the WildFly config file.

I suppose it would be a good thing, I just haven't yet experimented with how to do it. It would basically mean somehow mounting the UI jar into deployments on-the-fly. There is an issue for it: https://github.com/wildfly-extras/wildfly-graphql-feature-pack/issues/7
